---
- hosts: all
  remote_user: devshell
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"

    - name: Retrieve pending updates
      shell: apt list --upgradable
      register: apt_upgrades
      changed_when: False
      when: ansible_os_family == "Debian"

    - name: Display packages that can be updated
      debug:
        msg: "{{ apt_upgrades.stdout_lines }}"
      when: ansible_os_family == "Debian"

    - name: Check if data is safe
      assert:
        that:
          - "apt_upgrades['stdout_lines'] | regex_search(';') == None"
        fail_msg: "Data contains semi-colon character which could be an attemptive of SQL injection."
